#!/bin/bash

if [[ -z "$1" ]]; then
  echo "syntax:  cme-cloud [start stop restart update]"
  exit 1
fi

if [[ "$1" == "start" || "$1" == "restart" ]]; then
  echo "Checking to see if the Content Management Engine is already running . . . "
  id=$(docker ps | grep cme-cloud | awk '{print $1}')
  if [[ ${#id} != 0 ]]; then
    echo "found.  stopping."
    docker stop $id
  else
    echo "false."
  fi
  echo "Starting the Content Management Engine . . ."
  docker run -d -p 8081:80 andrewhald/cme-cloud /var/www/html/cme-cloud/start-cme-cloud
elif [[ "$1" == "update" ]]; then
  echo "Checking for an existing instance of the Content Management Engine . . . "
  id=$(docker ps | grep cme-cloud | awk '{print $1}')
  if [[ ${#id} != 0 ]]; then
    echo "found.  stopping. "
    docker stop $id
  fi
  echo "Updating the Content Management Engine . . . "
  echo "Pulling andrewhald/cme-cloud:latest . . . "
  docker pull andrewhald/cme-cloud:latest
  echo "Starting the newest version of the Content Management Engine . . . " 
  docker run -d -p 8081:80 andrewhald/cme-cloud /var/www/html/cme-cloud/start-cme-cloud
elif [[ "$1" == "stop" ]]; then
  echo "Stopping the Content Management Engine . . ."
  id=$(docker ps | grep cme-cloud | awk '{print $1}')
  if [[ ${#id} != 0 ]]; then
    docker stop $id
  else
    echo "cme is not currently running. "
  fi
else
  echo "error:  the only valid options are start, stop, restart and update."
fi

